server:
  port: 8081

spring:
  #上传文件大小设置
  servlet:
    multipart:
      enabled: true
      max-file-size: 931775308
      max-request-size: 1000MB

  #用于postman避开security检验
#  security:
#   user:
#     name: phw
#     password: phw

  #强制开启循环依赖
  main:
    allow-circular-references: true

  # nacos配置相关
  application:
    name: stpam-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848

  aop:
    proxy-target-class: true #true为使用CGLIB代理


  #  数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      mainsource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/stpam?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: admin
        password: admin123456
        # 初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,log4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        # 合并多个DruidDataSource的监控数据
        useGlobalDataSourceStat: true



mybatis-plus:
  #mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #数据返回类型别名
  type-aliases-package: com.example.server.pojo
  global-config:
    refresh-mapper: true
    #驼峰下划线转换
    column-underline: false
  configuration:
    #关闭自动驼峰命名，默认打开，但是数据库里有驼峰就会报错
    map-underscore-to-camel-case: false

## Mybatis SQL 打印（方法接口的包，不是Mapper。xml的包）
logging:
  level:
    com.example.server.mapper: debug


jwt:
  #jwt存储的请求头
  tokenHeader: Authorization
  #jwt加密解密用的密钥
  secret: stpam-secret
  #jwt超期限时间（60*60*24）
  expiration: 604800
  #jwt负载中拿到开头
  tokenHead: Bearer

